;this file for FamiTone4.2 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


hotdance2020_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,317,264 ; Promienie
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Big in Japan
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Broken Heart

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env3
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$02,$ce,$03,$cd,$03,$cc,$03,$cb,$03,$ca,$03,$c9,$03,$c8,$03
	.byte $c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$03,$c0,$00
	.byte $1e
@env2:
	.byte $cf,$ce,$cc,$cb,$c9,$c8,$c6,$c4,$c3,$c2,$c0,$00,$0a
@env3:
	.byte $c0,$c2,$c2,$c0,$be,$be,$c0,$be,$be,$c0,$c0,$be,$be,$c0,$00,$04


; Promienie
@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $80,$25,$81,$00,$81,$25,$00,$25,$81,$00,$81,$25,$81,$00,$81,$25
	.byte $81,$00,$81,$25,$00,$25,$81,$00,$81,$25,$81,$00,$81,$25,$85
@ref1:
	.byte $27,$81,$00,$81,$27,$00,$27,$81,$00,$81,$27,$81,$00,$81,$27,$81
	.byte $00,$81,$27,$00,$27,$81,$00,$81,$27,$81,$00,$81,$27,$85
@ref2:
	.byte $28,$81,$00,$81,$28,$00,$28,$81,$00,$81,$28,$81,$00,$81,$28,$81
	.byte $00,$81,$28,$00,$28,$81,$00,$81,$28,$81,$00,$81,$28,$85
@ref3:
	.byte $2a,$8d,$29,$8d,$2a,$8d,$2c,$8d
@ref4:
	.byte $2a,$85,$2d,$85,$2a,$85,$2d,$85,$25,$85,$2d,$8d,$27,$85
@ref5:
	.byte $87,$27,$8d,$28,$85,$27,$85,$2a,$85,$28,$85,$2a,$85
@ref6:
	.byte $2c,$85,$2f,$85,$2c,$85,$2f,$85,$2d,$85,$2f,$85,$2c,$85,$28,$85
@ref7:
	.byte $87,$28,$8d,$2a,$85,$28,$85,$2a,$85,$28,$85,$2c,$85
@ref8:
	.byte $2a,$85,$2d,$85,$2a,$85,$2d,$85,$31,$85,$2d,$8d,$27,$85
@ref9:
	.byte $87,$27,$8d,$34,$85,$33,$85,$34,$85,$2f,$85,$25,$85
@ref10:
	.byte $8f,$25,$9d
@ref11:
	.byte $23,$85,$25,$a5
@ref12:
	.byte $38,$85,$38,$8d,$36,$a5
@ref13:
	.byte $36,$85,$38,$8d,$33,$a5
@ref14:
	.byte $38,$8d,$34,$85,$34,$8d,$31,$95
@ref15:
	.byte $bf
@ref16:
	.byte $38,$85,$38,$8d,$39,$8d,$3b,$95
@ref17:
	.byte $3b,$8d,$3b,$85,$39,$8d,$36,$95
@ref18:
	.byte $36,$8d,$3b,$85,$38,$95
@ref19:
	.byte $af
@ref20:
	.byte $87,$34,$b5
@ref21:
	.byte $bf
@ref22:
	.byte $34,$81,$00,$81,$39,$81,$00,$81,$34,$81,$00,$81,$39,$85,$34,$85
	.byte $31,$8d,$33,$85
@ref23:
	.byte $87,$33,$8d,$34,$85,$33,$8d,$36,$8d
@ref24:
	.byte $33,$81,$00,$81,$38,$81,$00,$81,$33,$81,$00,$81,$38,$85,$33,$85
	.byte $31,$8d,$31,$85
@ref25:
	.byte $87,$31,$8d,$33,$85,$31,$8d,$34,$8d
@ref26:
	.byte $38,$85,$36,$81,$00,$81,$34,$81,$00,$81,$36,$85,$38,$85,$36,$95
@ref27:
	.byte $34,$81,$00,$81,$33,$81,$00,$81,$33,$81,$00,$81,$33,$85,$36,$85
	.byte $34,$95
@ref28:
	.byte $38,$9d,$39,$89
@ref29:
	.byte $93,$3b,$95
@ref30:
	.byte $34,$85,$36,$89
@ref31:
	.byte $83,$38,$8d
	.byte $ff,$14
	.word @ref22
	.byte $ff,$09
	.word @ref23
@ref34:
	.byte $38,$81,$00,$81,$3b,$81,$00,$81,$38,$81,$00,$81,$3b,$81,$00,$81
	.byte $38,$85,$39,$85,$38,$85,$34,$85
@ref35:
	.byte $87,$34,$8d,$36,$85,$34,$8d,$38,$8d
	.byte $ff,$10
	.word @ref26
@ref37:
	.byte $34,$81,$00,$81,$33,$81,$00,$81,$33,$81,$00,$81,$33,$85,$36,$85
	.byte $34,$8d,$31,$85
@ref38:
	.byte $87,$31,$95,$2f,$8d,$31,$85,$31,$85
@ref39:
	.byte $bf
@song0ch0loop:
@ref40:
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $ff,$20
	.word @ref40
@ref42:
	.byte $83
	.byte $fd
	.word @song0ch0loop

; Promienie
@song0ch1:
@ref43:
	.byte $80,$19,$81,$00,$81,$19,$00,$19,$81,$00,$81,$19,$81,$00,$81,$19
	.byte $81,$00,$81,$19,$00,$19,$81,$00,$81,$19,$81,$00,$81,$19,$85
@ref44:
	.byte $1b,$81,$00,$81,$1b,$00,$1b,$81,$00,$81,$1b,$81,$00,$81,$1b,$81
	.byte $00,$81,$1b,$00,$1b,$81,$00,$81,$1b,$81,$00,$81,$1b,$85
@ref45:
	.byte $1c,$81,$00,$81,$1c,$00,$1c,$81,$00,$81,$1c,$81,$00,$81,$1c,$81
	.byte $00,$81,$1c,$00,$1c,$81,$00,$81,$1c,$81,$00,$81,$1c,$85
@ref46:
	.byte $1e,$8d,$1d,$8d,$1e,$8d,$20,$8d
@ref47:
	.byte $36,$85,$21,$85,$1e,$85,$21,$85,$19,$85,$21,$8d,$1b,$85
@ref48:
	.byte $87,$1b,$8d,$1c,$85,$1b,$85,$1e,$85,$1c,$85,$1e,$85
@ref49:
	.byte $38,$85,$23,$85,$34,$85,$23,$85,$33,$85,$34,$85,$2f,$85,$31,$85
@ref50:
	.byte $87,$1c,$8d,$1e,$85,$1c,$85,$1e,$85,$1c,$85,$20,$85
@ref51:
	.byte $39,$85,$21,$85,$36,$85,$21,$85,$36,$85,$34,$8d,$33,$85
@ref52:
	.byte $87,$1b,$8d,$28,$85,$27,$85,$28,$85,$23,$85,$31,$85
@ref53:
	.byte $8f,$19,$9d
@ref54:
	.byte $2f,$85,$31,$a5
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $af,$31,$8d
@ref58:
	.byte $34,$85,$33,$85,$2f,$85,$31,$a5
@ref59:
	.byte $2f,$85,$2f,$8d,$36,$8d,$38,$95
@ref60:
	.byte $38,$8d,$38,$85,$36,$8d,$33,$95
@ref61:
	.byte $33,$8d,$38,$85,$28,$95
@ref62:
	.byte $34,$8d,$34,$85,$33,$8d,$31,$85
@ref63:
	.byte $87,$2c,$b5
@ref64:
	.byte $bf
@ref65:
	.byte $25,$81,$00,$81,$31,$81,$00,$81,$25,$81,$00,$81,$31,$81,$00,$81
	.byte $31,$81,$00,$81,$25,$85,$00,$85,$2a,$85
@ref66:
	.byte $00,$85,$2a,$85,$00,$85,$2c,$81,$00,$81,$2a,$85,$00,$85,$2d,$8d
@ref67:
	.byte $2a,$81,$00,$81,$2f,$81,$00,$81,$2a,$81,$00,$81,$2f,$81,$00,$81
	.byte $2a,$81,$00,$81,$28,$85,$00,$85,$28,$85
@ref68:
	.byte $00,$85,$28,$85,$00,$85,$2a,$81,$00,$81,$28,$8d,$2c,$8d
@ref69:
	.byte $28,$85,$2a,$81,$00,$81,$2d,$81,$00,$81,$2a,$85,$2f,$85,$2d,$95
@ref70:
	.byte $2a,$81,$00,$81,$2a,$81,$00,$81,$2a,$81,$00,$81,$2a,$85,$2d,$85
	.byte $2c,$95
@ref71:
	.byte $28,$9d,$2a,$89
@ref72:
	.byte $93,$2c,$95
@ref73:
	.byte $2c,$85,$2d,$89
@ref74:
	.byte $83,$2f,$8d
	.byte $ff,$1a
	.word @ref65
	.byte $ff,$10
	.word @ref66
@ref77:
	.byte $34,$81,$00,$81,$2c,$81,$00,$81,$34,$81,$00,$81,$2c,$85,$34,$85
	.byte $2a,$85,$28,$85,$25,$85
@ref78:
	.byte $87,$25,$8d,$33,$85,$31,$8d,$28,$8d
	.byte $ff,$10
	.word @ref69
@ref80:
	.byte $2a,$81,$00,$81,$2a,$81,$00,$81,$2a,$81,$00,$81,$2a,$85,$2d,$85
	.byte $2c,$8d,$28,$85
@ref81:
	.byte $87,$28,$b5
@ref82:
	.byte $bf
@song0ch1loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
@ref85:
	.byte $83
	.byte $fd
	.word @song0ch1loop

; Promienie
@song0ch2:
@ref86:
	.byte $00,$85,$80,$25,$85,$00,$85,$25,$85,$00,$85,$25,$85,$23,$85,$20
	.byte $85
@ref87:
	.byte $00,$85,$25,$85,$00,$85,$25,$85,$00,$85,$25,$85,$28,$85,$2a,$85
@ref88:
	.byte $00,$85,$25,$85,$00,$85,$25,$85,$00,$85,$25,$85,$23,$85,$20,$85
@ref89:
	.byte $00,$bd
@ref90:
	.byte $87,$1e,$85,$00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$1e,$85
@ref91:
	.byte $00,$85,$23,$85,$00,$85,$23,$85,$00,$85,$23,$85,$00,$85,$23,$85
@ref92:
	.byte $00,$85,$1c,$85,$00,$85,$1c,$85,$00,$85,$1c,$85,$00,$85,$1c,$85
@ref93:
	.byte $00,$85,$21,$85,$00,$85,$21,$85,$00,$85,$21,$85,$00,$85,$21,$85
@ref94:
	.byte $00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$1e,$85
@ref95:
	.byte $00,$85,$20,$85,$00,$85,$20,$85,$00,$85,$20,$85,$00,$85,$20,$85
	.byte $ff,$0c
	.word @ref87
@ref97:
	.byte $00,$85,$25,$85,$00,$9d
@ref98:
	.byte $9f,$00,$85,$1e,$85,$00,$85,$1e,$85
@ref99:
	.byte $00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$20,$85,$00,$85,$20,$85
@ref100:
	.byte $00,$85,$20,$85,$00,$85,$20,$85,$00,$85,$25,$85,$00,$85,$25,$85
@ref101:
	.byte $00,$85,$25,$85,$00,$85,$23,$85,$00,$85,$25,$85,$00,$85,$25,$85
@ref102:
	.byte $00,$85,$25,$85,$00,$85,$21,$85,$00,$85,$1e,$85,$00,$85,$1e,$85
@ref103:
	.byte $00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$23,$85,$00,$85,$23,$85
@ref104:
	.byte $00,$85,$23,$85,$00,$85,$23,$85,$00,$85,$28,$85
@ref105:
	.byte $00,$85,$28,$85,$00,$85,$28,$85,$00,$85,$28,$85
@ref106:
	.byte $00,$85,$25,$85,$00,$ad
@ref107:
	.byte $bf
@ref108:
	.byte $00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$1e,$85,$00,$85,$23,$85
	.byte $ff,$10
	.word @ref91
@ref110:
	.byte $00,$85,$20,$85,$00,$85,$20,$85,$00,$85,$20,$85,$00,$85,$25,$85
@ref111:
	.byte $00,$85,$25,$85,$00,$85,$25,$85,$00,$85,$25,$85,$00,$85,$25,$85
	.byte $ff,$10
	.word @ref94
@ref113:
	.byte $00,$85,$20,$85,$00,$85,$20,$85,$00,$8d,$20,$81,$00,$81,$20,$85
@ref114:
	.byte $00,$85,$25,$85,$00,$85,$25,$85,$00,$85,$25,$81
@ref115:
	.byte $83,$00,$85,$27,$85,$00,$85,$27,$85,$00,$85
@ref116:
	.byte $25,$85,$00,$85,$27,$81
	.byte $ff,$05
	.word @ref115
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref91
	.byte $ff,$10
	.word @ref110
	.byte $ff,$10
	.word @ref111
	.byte $ff,$10
	.word @ref94
	.byte $ff,$10
	.word @ref113
	.byte $ff,$10
	.word @ref111
@ref125:
	.byte $00,$bd
@song0ch2loop:
@ref126:
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $ff,$20
	.word @ref126
@ref128:
	.byte $83
	.byte $fd
	.word @song0ch2loop

; Promienie
@song0ch3:
@ref129:
	.byte $84,$02,$85,$82,$0c,$85,$01,$85,$0c,$85,$84,$02,$85,$82,$0c,$85
	.byte $01,$85,$0c,$85
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$0c
	.word @ref129
@ref140:
	.byte $01,$85,$0c,$85,$84,$02,$85,$82,$0c,$85,$01,$85,$0c,$85
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$0c
	.word @ref129
	.byte $ff,$0c
	.word @ref140
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
@ref157:
	.byte $84,$02,$85,$82,$0c,$85,$01,$85,$0c,$85,$84,$02,$85,$82,$0c,$81
@ref158:
	.byte $83,$01,$85,$0c,$85,$84,$02,$85,$82,$0c,$85,$01,$85
@ref159:
	.byte $0c,$85,$01,$85,$0c,$81
@ref160:
	.byte $83,$84,$02,$85,$82,$0c,$85
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
	.byte $ff,$10
	.word @ref129
@song0ch3loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
@ref171:
	.byte $83
	.byte $fd
	.word @song0ch3loop

; Promienie
@song0ch4:
@ref172:
	.byte $bf
@ref173:
	.byte $bf
@ref174:
	.byte $bf
@ref175:
	.byte $bf
@ref176:
	.byte $bf
@ref177:
	.byte $bf
@ref178:
	.byte $bf
@ref179:
	.byte $bf
@ref180:
	.byte $bf
@ref181:
	.byte $bf
@ref182:
	.byte $af
@ref183:
	.byte $af
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
@ref190:
	.byte $af
@ref191:
	.byte $af
@ref192:
	.byte $bf
@ref193:
	.byte $bf
@ref194:
	.byte $bf
@ref195:
	.byte $bf
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $ab
@ref201:
	.byte $ab
@ref202:
	.byte $93
@ref203:
	.byte $93
@ref204:
	.byte $bf
@ref205:
	.byte $bf
@ref206:
	.byte $bf
@ref207:
	.byte $bf
@ref208:
	.byte $bf
@ref209:
	.byte $bf
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@song0ch4loop:
	.byte $ff,$20
	.word @ref126
	.byte $ff,$20
	.word @ref126
@ref214:
	.byte $83
	.byte $fd
	.word @song0ch4loop


; Big in Japan
@song1ch0:
	.byte $fb,$06
@ref215:
	.byte $80,$2a,$81,$2d,$81,$2a,$28,$2a,$2d,$8f,$2a,$81,$2d,$81,$2a,$28
	.byte $2a,$2f,$87,$2a,$85
@ref216:
	.byte $2a,$81,$2d,$81,$2a,$28,$2a,$2d,$81,$2d,$2a,$81,$28,$81,$2a,$81
	.byte $2d,$83,$2d,$83,$2d,$81,$31,$83,$34,$83,$31,$81
@ref217:
	.byte $2a,$81,$2d,$81,$2a,$28,$2a,$2d,$81,$2d,$2a,$81,$28,$81,$2a,$81
	.byte $2a,$81,$2d,$81,$28,$2a,$28,$2f,$81,$2f,$81,$2f,$2a,$81,$2d,$81
@ref218:
	.byte $2a,$81,$2d,$81,$2a,$28,$2a,$2d,$81,$2d,$2a,$81,$28,$81,$2a,$81
	.byte $2d,$83,$2d,$83,$2d,$81,$31,$81,$2f,$34,$81,$2f,$31,$81
@ref219:
	.byte $00,$85,$36,$81,$39,$81,$39,$39,$81,$38,$83,$36,$89,$36,$81,$39
	.byte $81,$38,$81,$39,$81,$3b,$39,$81,$38
@ref220:
	.byte $83,$38,$81,$38,$36,$81,$36,$83,$38,$81,$36,$81,$34,$81,$31,$9d
@ref221:
	.byte $00,$85,$36,$81,$39,$81,$39,$81,$39,$38,$83,$36,$89,$36,$81,$39
	.byte $81,$3b,$81,$39,$81,$38,$81,$3b,$81
@ref222:
	.byte $39,$81,$38,$81,$36,$36,$81,$39,$83,$3b,$81,$39,$81,$38,$81,$36
	.byte $81,$35,$85,$31,$91
@ref223:
	.byte $00,$85,$36,$81,$39,$81,$3b,$39,$81,$38,$83,$36,$81,$34,$85,$3b
	.byte $39,$81,$38,$83,$39,$81,$3b,$81,$39,$81
@ref224:
	.byte $32,$85,$32,$34,$83,$39,$36,$83,$34,$81,$38,$81,$39,$83,$36,$38
	.byte $95
	.byte $ff,$1a
	.word @ref223
@ref226:
	.byte $32,$81,$32,$81,$32,$34,$83,$39,$36,$83,$34,$81,$38,$81,$39,$38
	.byte $36,$38,$89,$36,$36,$36,$36,$38,$39,$39
@ref227:
	.byte $39,$39,$36,$36,$83,$36,$81,$36,$32,$83,$36,$38,$36,$34,$34,$89
	.byte $38,$81,$39,$31,$83,$31,$31,$31,$32
@ref228:
	.byte $32,$32,$34,$36,$36,$83,$38,$36,$81,$38,$81,$38,$81,$39,$81,$38
	.byte $8f,$36,$36,$36,$36,$38,$39,$39
@ref229:
	.byte $39,$39,$36,$36,$83,$3d,$81,$39,$36,$83,$39,$81,$38,$34,$83,$36
	.byte $81,$39,$81,$38,$81,$34,$85,$39,$81,$36,$34
@ref230:
	.byte $83,$36,$81,$36,$81,$39,$81,$38,$83,$36,$83,$38,$81,$37,$38,$8d
	.byte $39,$39,$39,$39,$38,$36,$36
	.byte $ff,$19
	.word @ref227
	.byte $ff,$18
	.word @ref228
	.byte $ff,$1b
	.word @ref229
	.byte $ff,$17
	.word @ref230
	.byte $ff,$1a
	.word @ref223
	.byte $ff,$11
	.word @ref224
	.byte $ff,$1a
	.word @ref223
	.byte $ff,$1a
	.word @ref226
	.byte $ff,$19
	.word @ref227
	.byte $ff,$18
	.word @ref228
	.byte $ff,$1b
	.word @ref229
	.byte $ff,$17
	.word @ref230
	.byte $ff,$19
	.word @ref227
	.byte $ff,$18
	.word @ref228
	.byte $ff,$1b
	.word @ref229
	.byte $ff,$17
	.word @ref230
@ref247:
	.byte $9f
@ref248:
	.byte $00,$9d
@song1ch0loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
@ref251:
	.byte $83
	.byte $fd
	.word @song1ch0loop

; Big in Japan
@song1ch1:
@ref252:
	.byte $00,$bd
@ref253:
	.byte $bf
@ref254:
	.byte $00,$bd
@ref255:
	.byte $bf
@ref256:
	.byte $80,$2d,$8d,$2d,$8d,$26,$8d,$26,$8d
@ref257:
	.byte $28,$8d,$28,$8d,$25,$8d,$25,$8d
@ref258:
	.byte $2d,$8d,$2d,$8d,$26,$8d,$26,$8d
	.byte $ff,$08
	.word @ref257
@ref260:
	.byte $2a,$89,$2a,$81,$26,$85,$26,$85,$28,$8d,$25,$85,$25,$85
@ref261:
	.byte $26,$8d,$23,$8d,$25,$83,$25,$83,$25,$81,$31,$85,$25,$85
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref261
	.byte $ff,$0e
	.word @ref260
@ref265:
	.byte $26,$8d,$23,$8d,$25,$83,$25,$83,$25,$81,$25,$85,$25,$85
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref261
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref261
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
	.byte $ff,$0e
	.word @ref260
	.byte $ff,$0e
	.word @ref265
@ref284:
	.byte $00,$9d
@ref285:
	.byte $9f
@song1ch1loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
@ref288:
	.byte $83
	.byte $fd
	.word @song1ch1loop

; Big in Japan
@song1ch2:
@ref289:
	.byte $80,$1e,$1e,$81,$1e,$1e,$81,$1e,$1e,$1e,$1e,$81,$1e,$1e,$81,$1e
	.byte $1e,$1a,$1a,$81,$1a,$1a,$81,$1a,$1a,$1a,$1a,$81,$1a,$1a,$81,$1a
	.byte $1a
@ref290:
	.byte $1c,$1c,$81,$1c,$1c,$81,$1c,$1c,$1c,$1c,$81,$1c,$1c,$81,$1c,$1c
	.byte $19,$19,$81,$19,$19,$81,$19,$19,$19,$19,$81,$19,$19,$81,$19,$19
@ref291:
	.byte $1e,$1e,$81,$1e,$1e,$81,$1e,$1e,$1e,$1e,$81,$1e,$1e,$81,$1e,$1e
	.byte $1a,$1a,$81,$1a,$1a,$81,$1a,$1a,$1a,$1a,$81,$1a,$1a,$81,$1a,$1a
	.byte $ff,$20
	.word @ref290
	.byte $ff,$20
	.word @ref291
	.byte $ff,$20
	.word @ref290
	.byte $ff,$20
	.word @ref291
	.byte $ff,$20
	.word @ref290
@ref297:
	.byte $1e,$1e,$81,$1e,$1e,$81,$1e,$1e,$1a,$26,$81,$1a,$26,$81,$1a,$26
	.byte $1c,$1c,$81,$1c,$1c,$81,$1c,$1c,$19,$25,$81,$19,$25,$81,$19,$25
@ref298:
	.byte $1a,$1a,$81,$1a,$1a,$81,$1a,$1a,$17,$23,$81,$17,$23,$81,$17,$23
	.byte $19,$19,$81,$19,$19,$81,$19,$19,$19,$25,$81,$19,$25,$81,$19,$25
	.byte $ff,$20
	.word @ref297
	.byte $ff,$20
	.word @ref298
@ref301:
	.byte $1e,$1e,$81,$1e,$1e,$81,$1e,$1e,$1a,$1a,$81,$1a,$1a,$81,$1a,$1a
	.byte $1c,$1c,$81,$1c,$1c,$81,$1c,$1c,$19,$19,$81,$19,$19,$81,$19,$19
@ref302:
	.byte $1a,$1a,$81,$1a,$1a,$81,$1a,$1a,$17,$17,$81,$17,$17,$81,$17,$17
	.byte $19,$19,$81,$19,$19,$81,$19,$19,$19,$25,$81,$19,$25,$81,$19,$25
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref297
	.byte $ff,$20
	.word @ref298
	.byte $ff,$20
	.word @ref297
	.byte $ff,$20
	.word @ref298
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
	.byte $ff,$20
	.word @ref301
	.byte $ff,$20
	.word @ref302
@ref321:
	.byte $9f
@ref322:
	.byte $00,$9d
@song1ch2loop:
	.byte $ff,$20
	.word @ref126
	.byte $ff,$20
	.word @ref126
@ref325:
	.byte $83
	.byte $fd
	.word @song1ch2loop

; Big in Japan
@song1ch3:
@ref326:
	.byte $84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81
	.byte $01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02
	.byte $81,$82,$0c,$81,$01,$81,$0c,$81
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$10
	.word @ref326
	.byte $ff,$10
	.word @ref326
@song1ch3loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
@ref362:
	.byte $83
	.byte $fd
	.word @song1ch3loop

; Big in Japan
@song1ch4:
@ref363:
	.byte $bf
@ref364:
	.byte $bf
@ref365:
	.byte $bf
@ref366:
	.byte $bf
@ref367:
	.byte $bf
@ref368:
	.byte $bf
@ref369:
	.byte $bf
@ref370:
	.byte $bf
@ref371:
	.byte $bf
@ref372:
	.byte $bf
@ref373:
	.byte $bf
@ref374:
	.byte $bf
@ref375:
	.byte $bf
@ref376:
	.byte $bf
@ref377:
	.byte $bf
@ref378:
	.byte $bf
@ref379:
	.byte $bf
@ref380:
	.byte $bf
@ref381:
	.byte $bf
@ref382:
	.byte $bf
@ref383:
	.byte $bf
@ref384:
	.byte $bf
@ref385:
	.byte $bf
@ref386:
	.byte $bf
@ref387:
	.byte $bf
@ref388:
	.byte $bf
@ref389:
	.byte $bf
@ref390:
	.byte $bf
@ref391:
	.byte $bf
@ref392:
	.byte $bf
@ref393:
	.byte $bf
@ref394:
	.byte $bf
@ref395:
	.byte $9f
@ref396:
	.byte $9f
@song1ch4loop:
	.byte $ff,$20
	.word @ref126
	.byte $ff,$20
	.word @ref126
@ref399:
	.byte $83
	.byte $fd
	.word @song1ch4loop


; Broken Heart
@song2ch0:
	.byte $fb,$06
@ref400:
	.byte $bf
@ref401:
	.byte $bf
@ref402:
	.byte $83,$80,$2f,$81,$2f,$81,$2d,$81,$2c,$81,$00,$2c,$81,$00,$2c,$83
	.byte $00,$2f,$00,$2f,$00,$2f,$00,$2f,$81,$00,$31,$83,$2d,$81
@ref403:
	.byte $81,$00,$2d,$81,$2d,$81,$2c,$81,$2a,$81,$00,$2a,$81,$00,$2a,$83
	.byte $00,$2d,$00,$2d,$00,$2d,$00,$2d,$81,$00,$2f,$83,$2c,$81
@ref404:
	.byte $83,$28,$81,$28,$81,$2a,$81,$2c,$81,$00,$2c,$81,$00,$2c,$83,$00
	.byte $2c,$00,$2c,$00,$2c,$00,$2c,$81,$00,$2d,$83,$2a,$81
@ref405:
	.byte $81,$00,$2a,$81,$2a,$81,$28,$81,$27,$81,$00,$27,$81,$00,$27,$83
	.byte $00,$27,$00,$27,$00,$27,$00,$27,$81,$00,$28,$83,$28,$81
@ref406:
	.byte $83,$2f,$81,$2f,$81,$2d,$81,$2c,$81,$00,$2c,$81,$00,$2c,$83,$00
	.byte $2f,$00,$2f,$00,$2f,$00,$2f,$81,$00,$31,$83,$2d,$81
	.byte $ff,$1e
	.word @ref403
	.byte $ff,$1d
	.word @ref404
@ref409:
	.byte $81,$00,$2a,$81,$2a,$81,$28,$81,$27,$81,$00,$27,$81,$00,$27,$83
	.byte $00,$27,$00,$27,$00,$27,$00,$27,$81,$00,$28,$83,$25,$81
@ref410:
	.byte $87,$2c,$85,$2d,$85,$2f,$85,$31,$81,$00,$31,$81,$00,$31,$81,$2d
	.byte $85,$2c,$81,$2a,$81
@ref411:
	.byte $87,$2a,$85,$2c,$85,$2d,$85,$2f,$81,$00,$2f,$81,$00,$2f,$81,$2c
	.byte $85,$2a,$81,$28,$81
@ref412:
	.byte $87,$28,$85,$2a,$85,$2c,$85,$2d,$83,$2d,$83,$2d,$81,$2a,$85,$28
	.byte $81,$27,$81
@ref413:
	.byte $87,$27,$85,$28,$83,$27,$83,$25,$89,$25,$85,$25,$85,$23,$81,$25
	.byte $81
@ref414:
	.byte $87
	.byte $ff,$1d
	.word @ref406
	.byte $ff,$1e
	.word @ref403
	.byte $ff,$1d
	.word @ref404
	.byte $ff,$1e
	.word @ref405
	.byte $ff,$1d
	.word @ref406
	.byte $ff,$1e
	.word @ref403
	.byte $ff,$1d
	.word @ref404
	.byte $ff,$1e
	.word @ref409
@ref423:
	.byte $83,$31,$81,$31,$81,$2f,$81,$2e,$81,$00,$2e,$81,$00,$2e,$83,$00
	.byte $31,$00,$31,$00,$31,$00,$31,$81,$00,$33,$83,$2f,$81
@ref424:
	.byte $81,$00,$2f,$81,$2f,$81,$2e,$81,$2c,$81,$00,$2c,$81,$00,$2c,$83
	.byte $00,$2f,$00,$2f,$00,$2f,$00,$2f,$81,$00,$31,$83,$2e,$81
@ref425:
	.byte $83,$2a,$81,$2a,$81,$2c,$81,$2e,$81,$00,$2e,$81,$00,$2e,$83,$00
	.byte $2e,$00,$2e,$00,$2e,$00,$2e,$81,$00,$2f,$83,$2c,$81
@ref426:
	.byte $81,$00,$2c,$81,$2c,$81,$2a,$81,$29,$81,$00,$29,$81,$00,$29,$83
	.byte $00,$29,$00,$29,$00,$29,$00,$29,$81,$00,$2a,$83,$2a,$81
	.byte $ff,$1d
	.word @ref423
	.byte $ff,$1e
	.word @ref424
	.byte $ff,$1d
	.word @ref425
@ref430:
	.byte $81,$00,$2c,$81,$2c,$81,$2a,$81,$29,$81,$00,$29,$81,$00,$29,$83
	.byte $00,$29,$00,$29,$00,$29,$00,$29,$81,$00,$2a,$83,$27,$81
@song2ch0loop:
@ref431:
	.byte $bf
@ref432:
	.byte $bf
@ref433:
	.byte $83
	.byte $fd
	.word @song2ch0loop

; Broken Heart
@song2ch1:
@ref434:
	.byte $bf
@ref435:
	.byte $bf
@ref436:
	.byte $83,$80,$2c,$89,$28,$83,$28,$83,$28,$85,$2c,$89,$2c,$83,$2d,$83
	.byte $2a,$81
@ref437:
	.byte $83,$2a,$89,$27,$83,$27,$83,$27,$85,$2a,$89,$2a,$83,$2c,$83,$28
	.byte $81
@ref438:
	.byte $83,$2c,$89,$28,$83,$28,$83,$28,$85,$28,$89,$28,$83,$2a,$83,$2d
	.byte $81
@ref439:
	.byte $83,$27,$89,$23,$83,$23,$83,$23,$85,$2a,$89,$2a,$83,$2c,$83,$2c
	.byte $81
@ref440:
	.byte $83,$2c,$89,$28,$83,$28,$83,$28,$85,$2c,$89,$2c,$83,$2d,$83,$2a
	.byte $81
	.byte $ff,$11
	.word @ref437
	.byte $ff,$11
	.word @ref438
@ref443:
	.byte $83,$27,$89,$23,$83,$23,$83,$23,$85,$2a,$99
	.byte $ff,$13
	.word @ref412
@ref445:
	.byte $87,$27,$85,$28,$85,$2a,$85,$2c,$83,$2c,$83,$2c,$81,$28,$85,$27
	.byte $81,$25,$81
@ref446:
	.byte $87,$25,$85,$27,$85,$28,$85,$2a,$83,$2a,$83,$2a,$81,$27,$85,$25
	.byte $85
@ref447:
	.byte $bf
@ref448:
	.byte $87
	.byte $ff,$11
	.word @ref440
	.byte $ff,$11
	.word @ref437
	.byte $ff,$11
	.word @ref438
	.byte $ff,$11
	.word @ref439
	.byte $ff,$11
	.word @ref440
	.byte $ff,$11
	.word @ref437
	.byte $ff,$11
	.word @ref438
	.byte $ff,$0b
	.word @ref443
@ref457:
	.byte $83,$2e,$89,$2a,$83,$2a,$83,$2a,$85,$2e,$89,$2e,$83,$2f,$83,$2c
	.byte $81
@ref458:
	.byte $83,$2c,$89,$29,$83,$29,$83,$29,$85,$2c,$89,$2c,$83,$2e,$83,$2a
	.byte $81
@ref459:
	.byte $83,$2e,$89,$2a,$83,$2a,$83,$2a,$85,$2a,$89,$2a,$83,$2c,$83,$2f
	.byte $81
@ref460:
	.byte $83,$29,$89,$25,$83,$25,$83,$25,$85,$2c,$89,$2c,$83,$2e,$83,$2e
	.byte $81
	.byte $ff,$11
	.word @ref457
	.byte $ff,$11
	.word @ref458
	.byte $ff,$11
	.word @ref459
@ref464:
	.byte $83,$29,$89,$25,$83,$25,$83,$25,$85,$2c,$99
@song2ch1loop:
@ref465:
	.byte $bf
@ref466:
	.byte $bf
@ref467:
	.byte $83
	.byte $fd
	.word @song2ch1loop

; Broken Heart
@song2ch2:
@ref468:
	.byte $bf
@ref469:
	.byte $bf
@ref470:
	.byte $83,$80,$2f,$89,$2c,$81,$00,$2c,$81,$00,$2c,$91,$2d,$81,$00,$2d
	.byte $81,$00,$2d,$81
@ref471:
	.byte $8f,$2a,$81,$00,$2a,$81,$00,$2a,$91,$2c,$81,$00,$2c,$81,$00,$2c
	.byte $81
@ref472:
	.byte $83,$2f,$89,$2c,$81,$00,$2c,$81,$00,$2c,$91,$2d,$81,$00,$2d,$81
	.byte $00,$2d,$81
	.byte $ff,$11
	.word @ref471
	.byte $ff,$13
	.word @ref472
	.byte $ff,$11
	.word @ref471
	.byte $ff,$13
	.word @ref472
@ref477:
	.byte $8f,$2a,$81,$00,$2a,$81,$00,$2a,$91,$27,$81,$00,$28,$81,$00,$25
	.byte $81
	.byte $ff,$15
	.word @ref410
	.byte $ff,$15
	.word @ref411
	.byte $ff,$13
	.word @ref412
	.byte $ff,$11
	.word @ref413
@ref482:
	.byte $87
	.byte $ff,$13
	.word @ref472
	.byte $ff,$11
	.word @ref471
	.byte $ff,$13
	.word @ref472
	.byte $ff,$11
	.word @ref471
	.byte $ff,$13
	.word @ref472
	.byte $ff,$11
	.word @ref471
	.byte $ff,$13
	.word @ref472
	.byte $ff,$11
	.word @ref477
@ref491:
	.byte $83,$31,$89,$2e,$81,$00,$2e,$81,$00,$2e,$91,$2f,$81,$00,$2f,$81
	.byte $00,$2f,$81
@ref492:
	.byte $8f,$2c,$81,$00,$2c,$81,$00,$2c,$91,$2e,$81,$00,$2e,$81,$00,$2e
	.byte $81
	.byte $ff,$13
	.word @ref491
	.byte $ff,$11
	.word @ref492
	.byte $ff,$13
	.word @ref491
	.byte $ff,$11
	.word @ref492
	.byte $ff,$13
	.word @ref491
@ref498:
	.byte $8f,$2c,$81,$00,$2c,$81,$00,$2c,$91,$29,$81,$00,$2a,$81,$00,$27
	.byte $81
@song2ch2loop:
@ref499:
	.byte $bf
@ref500:
	.byte $bf
@ref501:
	.byte $83
	.byte $fd
	.word @song2ch2loop

; Broken Heart
@song2ch3:
	.byte $ff,$20
	.word @ref326
@ref503:
	.byte $84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81
	.byte $01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02
	.byte $81,$02,$81,$02,$81,$02,$81
@ref504:
	.byte $83,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81,$01,$81
	.byte $0c,$81,$84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81,$82
	.byte $0c,$81,$01,$81,$0c,$81
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref503
@ref516:
	.byte $87
@ref517:
	.byte $02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81,$82,$0c,$81,$01
	.byte $81,$0c,$81,$84,$02,$81,$82,$0c,$81,$01,$81,$0c,$81,$84,$02,$81
	.byte $82,$0c,$81,$01,$81,$0c,$81
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref503
	.byte $ff,$1f
	.word @ref504
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref326
	.byte $ff,$20
	.word @ref503
@song2ch3loop:
@ref533:
	.byte $bf
@ref534:
	.byte $bf
@ref535:
	.byte $83
	.byte $fd
	.word @song2ch3loop

; Broken Heart
@song2ch4:
@ref536:
	.byte $bf
@ref537:
	.byte $bf
@ref538:
	.byte $bf
@ref539:
	.byte $bf
@ref540:
	.byte $bf
@ref541:
	.byte $bf
@ref542:
	.byte $bf
@ref543:
	.byte $bf
@ref544:
	.byte $bf
@ref545:
	.byte $bf
@ref546:
	.byte $bf
@ref547:
	.byte $bf
@ref548:
	.byte $bf
@ref549:
	.byte $bf
@ref550:
	.byte $87
@ref551:
	.byte $bf
@ref552:
	.byte $bf
@ref553:
	.byte $bf
@ref554:
	.byte $bf
@ref555:
	.byte $bf
@ref556:
	.byte $bf
@ref557:
	.byte $bf
@ref558:
	.byte $bf
@ref559:
	.byte $bf
@ref560:
	.byte $bf
@ref561:
	.byte $bf
@ref562:
	.byte $bf
@ref563:
	.byte $bf
@ref564:
	.byte $bf
@ref565:
	.byte $bf
@ref566:
	.byte $bf
@song2ch4loop:
@ref567:
	.byte $bf
@ref568:
	.byte $bf
@ref569:
	.byte $83
	.byte $fd
	.word @song2ch4loop
