;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $80,$3f,$81,$86,$82,$00,$05,$81,$64,$05,$81,$4b,$05,$81,$38,$05
	.byte $81,$29,$05,$81,$1f,$05,$81,$15,$05,$00
@sfx_pal_0:
	.byte $80,$3f,$81,$7c,$82,$00,$05,$81,$5d,$04,$81,$45,$04,$81,$34,$04
	.byte $81,$26,$04,$81,$1d,$04,$81,$14,$05,$00
